### ISSUE TITLE
add `createPrefixes` function for scss

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#637]
before
```scss
$prefix-alert: $prefix + "alert";

$alert-types: (
    "info": "blue",
    "danger": "red",
    "warning": "yellow",
    "success": "green",
    "default": "gray",
);

.#{$prefix-alert} {
    @apply flex items-center p-4 text-sm rounded-lg w-full;

    &-container {
        @apply fixed bottom-4 right-4 flex gap-4 w-full max-w-md;
    }

    &-close {
        @apply ms-auto -mx-1.5 -my-1.5 p-1.5 inline-flex items-center justify-center h-8 w-8 rounded-lg;
    }

    &-icon {
        @apply me-2;
    }


    @each $type, $color in $alert-types {
        &-type-#{$type} {
            @apply text-#{$color}-800 bg-#{$color}-50;

            .#{$prefix-theme-dark} & {
                @apply bg-gray-800 text-#{$color}-400;
            }

            .#{$prefix-alert}-close {
                @apply bg-#{$color}-50 text-#{$color}-500 hover:bg-#{$color}-200;

                &:hover {
                    @apply ring-2 ring-#{$color}-200;
                }

                &:focus {
                    @apply ring-2 ring-#{$color}-400;
                }


                .#{$prefix-theme-dark} & {
                    @apply bg-gray-800 text-#{$color}-400;
                }

                .#{$prefix-theme-dark} &:hover {
                    @apply bg-gray-700;
                }
            }
        }
    }
}

```
after
```scss
$prefixes: createPrefixes("alert", ('close', 'container', 'icon'));

$alert-types: (
    "info": "blue",
    "danger": "red",
    "warning": "yellow",
    "success": "green",
    "default": "gray",
);

.#{map-get($prefixes, "alert")} {
    @apply flex items-center p-4 text-sm rounded-lg w-full;

    .#{map-get($prefixes, "container")} {
        @apply fixed bottom-4 right-4 flex gap-4 w-full max-w-md;
    }

    .#{map-get($prefixes, "close")} {
        @apply ms-auto -mx-1.5 -my-1.5 p-1.5 inline-flex items-center justify-center h-8 w-8 rounded-lg;
    }

    .#{map-get($prefixes, "icon")} {
        @apply me-2;
    }


    @each $type, $color in $alert-types {
        &-type-#{$type} {
            @apply text-#{$color}-800 bg-#{$color}-50;

            .#{$prefix-theme-dark} & {
                @apply bg-gray-800 text-#{$color}-400;
            }

            .#{map-get($prefixes, 'close')} {
                @apply bg-#{$color}-50 text-#{$color}-500 hover:bg-#{$color}-200;

                &:hover {
                    @apply ring-2 ring-#{$color}-200;
                }

                &:focus {
                    @apply ring-2 ring-#{$color}-400;
                }


                .#{$prefix-theme-dark} & {
                    @apply bg-gray-800 text-#{$color}-400;
                }

                .#{$prefix-theme-dark} &:hover {
                    @apply bg-gray-700;
                }
            }
        }
    }
}
```
